---
kind: pipeline
type: kubernetes
name: default

steps:
- name: Elixir Build and Test
  image: harbor.xirion.net/hub/library/elixir
  commands:
    - apt-get update -y
    - apt-get install cargo python-pip -y
    - pip install lark-parser --upgrade
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix test
    - mix credo
