---
kind: pipeline
type: kubernetes
name: default

steps:
- name: Elixir Build and Test
  image: harbor.xirion.net/library/aoc2020
  commands:
    - pip install lark-parser --upgrade
    - yes | mix deps.get
    - mix test
    - mix credo
